name: ci

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  CI:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch}}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.version == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.6' # LTS
          - '1.7' # latest stable
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        arch:
          - x64
          - x86
        exclude:
          # Test 32-bit only on Linux
          - os: macos-latest
            arch: x86
          - os: windows-latest
            arch: x86
        include:
          - version: 'nightly'
            os: ubuntu-latest

    steps:

      # Setup environment
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
      - name: Cache artifacts
        uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-

      # Julia Dependencies
      - name: Install Julia dependencies
        uses: julia-actions/julia-buildpkg@latest

      # Run tests
      - name: Run Graphical test
        run:  julia --project -e 'using Pkg; Pkg.test(coverage=true)'

      # - name: Codecov
      #   uses: julia-actions/julia-uploadcodecov@latest
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  Skip:
    if: "contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Skip CI 🚫
        run: echo skip ci
