name: ci

on:
  push:
    branches: [master]
  pull_request:

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  CI:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch}}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10' # LTS (lowest supported `julia` version declared in `Project.toml`)
          - '1' # latest stable
        experimental:
          - false
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x64, x86]
        exclude:
          # Test 32-bit only on Linux
          - os: macos-latest
            arch: x86
          - os: windows-latest
            arch: x86
        include:
          - version: 'nightly'
            os: ubuntu-latest
            experimental: true

    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-processcoverage@latest
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          file: lcov.info

  Skip:
    if: "contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Skip CI 🚫
        run: echo skip ci
